#ifndef ARTD_STATIC_ASSERT

/* ARTD_STATIC_ASSERT macro derived from : boost/static_assert.hpp, suffix.hpp
 * (www.boost.org)
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifdef __cplusplus

#if 0


template <const int x, class StaticAssertionMessage> 
class StaticAssertionChecker;

template <class StaticAssertionMessage> 
class StaticAssertionChecker<1, StaticAssertionMessage> { };

template <int x> 
class StaticAssertionTest {};



#ifdef ARTD_WINDOWS

#define ARTD_STATIC_ASSERT(condition) \
	    typedef int ARTD_JOIN(STATIC_ASSERT_CHECK_,__LINE__); \
	    typedef StaticAssertionTest<sizeof(StaticAssertionChecker<(int)(condition),ARTD_JOIN(STATIC_ASSERT_CHECK_,__LINE__)>)>ARTD_JOIN(STATIC_ASSERT_ERROR_,__LINE__);

#else
	#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
	#pragma GCC diagnostic push

	#define ARTD_STATIC_ASSERT(condition) \
	    typedef int ARTD_JOIN(STATIC_ASSERT_CHECK_,__LINE__); \
	    typedef StaticAssertionTest<sizeof(StaticAssertionChecker<(int)(condition),ARTD_JOIN \
		(STATIC_ASSERT_CHECK_,__LINE__)>)>ARTD_JOIN(STATIC_ASSERT_ERROR_,__LINE__); 

	#pragma GCC diagnostic pop

#endif // not windows

#endif // 0


#define ARTD_STATIC_ASSERT(condition) static_assert(condition)


#else // not C++

	#define ARTD_STATIC_ASSERT(condition) \
		extern int ARTD_JOIN(STATIC_ASSERT_,__LINE__) [(condition) ? 1 : -1];

#endif // __cplusplus
#endif // ARTD_STATIC_ASSERT
